version: "3.9"

services:
  db:
    image: postgres:15.6-alpine
    volumes:
      - .PGDATA:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dstorage
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432
