services:
  db:
    image: postgres:15.6-alpine
    volumes:
      - .PGDATA_DRIZZLE:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dstorage
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432
  dstorage:
    build:
      context: .
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/src
      - '/src/node_modules'
    restart: always
